### ISSUE TITLE
jpype fails when using negbio in flask

### ISSUE THREAD

**Issue by staplet3** [ncbi-nlp/NegBio#27]
Hey guys, I wrapped NegBio in a flask app and had JPype fail within the Stanford Dependencies python library. I had to modify the JPypeBackend.py file to attach the thread to the JVM. I know you don't maintain this source code, but just a heads up. Changes start on line 45:
 
```
num_thread = jpype.isThreadAttachedToJVM()
if num_thread is not 1:
     jpype.attachThreadToJVM()
```

[JPypeBackend.py.zip](https://github.com/ncbi-nlp/NegBio/files/2944001/JPypeBackend.py.zip)
Attached the modified file here

**Comment by yfpeng** [comment]
Thank you! I have added your comment on the Wiki page.

**Comment by kaushikacharya** [comment]
I think the proper usage would be
```
if not jpype.isThreadAttachedToJVM():
            jpype.attachThreadToJVM()
```
as `isThreadAttachedToJVM()` returns boolean
https://github.com/jpype-project/jpype/blob/master/jpype/_core.py#L211

Otherwise as the following shows, 
`jpype.isThreadAttachedToJVM() is not 1`
will always return True irrespective of whether the function returns True or False.

```
>>> False is not 1
True
>>> True is not 1
True
>>> False is not 0
True
>>> True is not 0
True
```

**Comment by yfpeng** [comment]
Thank you!
